apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <name of your pvc>
  namespace: <your namespace name>
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi